src/Entity/Doctor.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DoctorRepository")
 */
class Doctor
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $specialization;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Visit", mappedBy="doctor")
     */
    private $visits;

    public function __construct()
    {
        $this->visits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getSpecialization(): ?string
    {
        return $this->specialization;
    }

    public function setSpecialization(?string $specialization): self
    {
        $this->specialization = $specialization;

        return $this;
    }

    /**
     * @return Collection|Visit[]
     */
    public function getVisits(): Collection
    {
        return $this->visits;
    }

    public function addVisit(Visit $visit): self
    {
        if (!$this->visits->contains($visit)) {
            $this->visits[] = $visit;
            $visit->setDoctor($this);
        }

        return $this;
    }

    public function removeVisit(Visit $visit): self
    {
        if ($this->visits->contains($visit)) {
            $this->visits->removeElement($visit);
            // set the owning side to null (unless already changed)
            if ($visit->getDoctor() === $this) {
                $visit->setDoctor(null);
            }
        }

        return $this;
    }

    public function getFreeVisitsCount(): int {
        $visits = $this->getVisits();
        $count = 0;
        foreach ($visits as $visit) {
            if ($visit->getStatus() == Visit::STATUS_OPEN) {
                $count++;
            }
        }
        return $count;
    }
}

src/Form/DoctorType.php
<?php

namespace App\Form;

use App\Entity\Doctor;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Email;

class DoctorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('first_name', null, ['label' => 'Imię'])
            ->add('last_name', null, ['label' => 'Nazwisko'])
            ->add('email', null, [
                'label' => 'Adres email',
                'constraints' => [
                    new Email([
                        'message' => 'Zła wartość',
                    ])
                ]
            ])
            ->add('phone', null, ['label' => 'Telefon'])
            ->add('specialization', null, ['label' => 'Specjalizacja'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Doctor::class,
        ]);
    }
}

src/Controller/Admin/DoctorController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Doctor;
use App\Form\DoctorType;
use App\Entity\Visit;
use App\Form\VisitType;
use App\Repository\DoctorRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/doctor")
 */
class DoctorController extends AbstractController
{

    /**
     * @Route("/new", name="doctor_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $doctor = new Doctor();
        $form = $this->createForm(DoctorType::class, $doctor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($doctor);
            $entityManager->flush();

            return $this->redirectToRoute('doctor_index');
        }

        return $this->render('admin/doctor/new.html.twig', [
            'doctor' => $doctor,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name="doctor_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Doctor $doctor): Response
    {
        $form = $this->createForm(DoctorType::class, $doctor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('doctor_index', [
                'id' => $doctor->getId(),
            ]);
        }

        return $this->render('admin/doctor/edit.html.twig', [
            'doctor' => $doctor,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="doctor_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Doctor $doctor): Response
    {
        if ($this->isCsrfTokenValid('delete'.$doctor->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($doctor);
            $entityManager->flush();
        }

        return $this->redirectToRoute('doctor_index');
    }

    /**
     * @Route("/{id}/visit/new", name="doctor_visit_new", methods={"GET", "POST"})
     */
    public function newVisit(Request $request, Doctor $doctor): Response
    {
        $visit = new Visit();
        $visit->setDoctor($doctor);
        $visit->setStatus(Visit::STATUS_OPEN);
        $form = $this->createForm(VisitType::class, $visit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($visit);
            $entityManager->flush();

            return $this->redirectToRoute('doctor_visit_index', [
                'id' => $doctor->getId(),
            ]);
        }

        return $this->render('admin/doctor/visit.new.html.twig', [
            'doctor' => $doctor,
            'visit' => $visit,
            'form' => $form->createView(),
        ]);
    }
}

src/Controller/DoctorController.php
<?php

namespace App\Controller;

use App\Entity\Doctor;
use App\Form\DoctorType;
use App\Entity\Visit;
use App\Form\VisitType;
use App\Repository\DoctorRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/doctor")
 */
class DoctorController extends AbstractController
{
    /**
     * @Route("/", name="doctor_index", methods={"GET"})
     */
    public function index(DoctorRepository $doctorRepository): Response
    {
        return $this->render('doctor/index.html.twig', [
            'doctors' => $doctorRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{id}", name="doctor_show", methods={"GET"})
     */
    public function show(Doctor $doctor): Response
    {
        return $this->render('doctor/show.html.twig', [
            'doctor' => $doctor,
        ]);
    }

    /**
     * @Route("/{id}/visit", name="doctor_visit_index", methods={"GET"})
     */
    public function visitIndex(Doctor $doctor): Response
    {
        return $this->render('doctor/visit.index.html.twig', [
          'doctor' => $doctor,
          'visits' => $doctor->getVisits(),
        ]);
    }
}

templates/doctor/index.html.twig
{% extends 'admin/layout.html.twig' %}

{% block title %}Doctor index{% endblock %}

{% block main %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
      <h1 class="h2">Lista lekarzy</h1>
    </div>
    {% if is_granted('ROLE_ADMIN') %}
        <div class="mb-3">
            <a href="{{ path('doctor_new') }}">Nowy lekarz <span data-feather="plus-circle"></span></a>
        </div>
    {% endif %}

    <table class="table">
        <thead>
            <tr>
                {% if is_granted('ROLE_ADMIN') %}
                    <th>Id</th>
                {% endif %}
                <th>Imię</th>
                <th>Nazwisko</th>
                <th>Email</th>
                <th>Telefon</th>
                <th>Specjalizacja</th>
                <th>Wolne wizyty</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for doctor in doctors %}
            {% set freeVisits = doctor.getFreeVisitsCount() %}
            <tr>
                {% if is_granted('ROLE_ADMIN') %}
                    <td>{{ doctor.id }}</td>
                {% endif %}
                <td>{{ doctor.firstName }}</td>
                <td>{{ doctor.lastName }}</td>
                <td>{{ doctor.email }}</td>
                <td>{{ doctor.phone }}</td>
                <td>{{ doctor.specialization }}</td>
                <td class="{{ freeVisits > 0 ? 'text-success' : 'text-danger' }}">{{ doctor.getFreeVisitsCount() }}</td>
                <td>
                {% if is_granted('ROLE_ADMIN') %}
                    <a href="{{ path('doctor_visit_index', {'id': doctor.id}) }}" class="pr-3">lista wizyt</a>
                    <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Akcja
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{{ path('doctor_show', {'id': doctor.id}) }}"><span data-feather="search"></span> szczegóły</a>
                        <a class="dropdown-item" href="{{ path('doctor_edit', {'id': doctor.id}) }}"><span data-feather="edit"></span> edycja</a>
                    </div>
                {% endif %}
                {% if freeVisits > 0 %}
                    <a class="btn btn-sm btn-success" href="{{ path('doctor_visit_index', {'id': doctor.id}) }}">zapisz się</a>
                {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">nie odnaleziono lekarzy w bazie</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/doctor/show.html.twig
{% extends 'admin/layout.html.twig' %}

{% block title %}Doctor{% endblock %}

{% block main %}
    <a href="{{ path('doctor_index') }}">
        <span data-feather="chevron-left"></span>
        powrót do listy Lekarzy
    </a>
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
      <h1 class="h2">{{ doctor.firstName }} {{doctor.lastName}} ({{ doctor.specialization }})</h1>
    </div>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ doctor.id }}</td>
            </tr>
            <tr>
                <th>Imię</th>
                <td>{{ doctor.firstName }}</td>
            </tr>
            <tr>
                <th>Nazwisko</th>
                <td>{{ doctor.lastName }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ doctor.email }}</td>
            </tr>
            <tr>
                <th>Telefon</th>
                <td>{{ doctor.phone }}</td>
            </tr>
            <tr>
                <th>Specjalizacja</th>
                <td>{{ doctor.specialization }}</td>
            </tr>
        </tbody>
    </table>

    {% if is_granted('ROLE_ADMIN') %}
        <div class="form-centered">
            <form action="{{ path('doctor_edit', {'id': doctor.id}) }}">
                <button class="btn btn-lg btn-success btn-block">Edytuj</button>
            </form>
            {{ include('default/_delete_form.html.twig', {'csrf': csrf_token('delete' ~ doctor.id), 'action': path('doctor_delete', {'id': doctor.id})}) }}
        </div>
    {% endif %}
{% endblock %}

templates/doctor/visit.index.html.twig
{% extends 'admin/layout.html.twig' %}

{% block title %}Doctor index{% endblock %}

{% block main %}
    <a href="{{ path('doctor_index') }}">
        <span data-feather="chevron-left"></span>
        powrót do listy Lekarzy
    </a>
    <div class="pt-3 pb-2 mb-3">
      <h1 class="h2">{{doctor.firstName}} {{doctor.lastName}} ({{doctor.specialization}})</h1>
      <p>Lista dostępnych wizyt</p>
    </div>
    {% if is_granted('ROLE_ADMIN') %}
        <div class="mb-3">
            <a href="{{ path('doctor_visit_new', {'id': doctor.id}) }}">Nowa wizyta lekarza <span data-feather="plus-circle"></span></a>
        </div>
    {% endif %}

    <table class="table">
        <thead>
            <tr>
              {% if is_granted('ROLE_ADMIN') %}
                  <th>Id</th>
              {% endif %}
              <th>Data</th>
              <th>Status</th>
              {% if is_granted('ROLE_ADMIN') %}
                <th>Pacjent</th>
                <th></th>
              {% endif %}
              <th></th>
            </tr>
        </thead>
        <tbody>
        {% for visit in visits %}
            <tr>
                {% if is_granted('ROLE_ADMIN') %}
                    <td>{{ visit.id }}</td>
                {% endif %}
                <td>{{ visit.date |date('d.m.Y H:i') }}</td>
                <td>
                    {% if visit.status == 'open' %}
                        <span class="text-success">Wolna</span>
                    {% else %}
                        <span class="text-danger">Zajęta</span>
                    {% endif %}
                </td>
                {% if is_granted('ROLE_ADMIN') %}
                    <td>
                        {% if visit.user %}
                            {{visit.user.firstName}} {{visit.user.lastName}}
                        {% endif %}
                    </td>
                {% endif %}
                <td>
                    {% if visit.status == 'open' %}
                        {{ include('default/_visit_sign_form.html.twig') }}
                    {% endif %}
                </td>
                {% if is_granted('ROLE_ADMIN') %}
                <td>
                    <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Akcja
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{{ path('visit_edit', {'id': visit.id}) }}"><span data-feather="edit"></span> edycja</a>
                    </div>
                </td>
                {% endif %}
            </tr>
        {% else %}
            <tr>
                <td colspan="7">nie odnaleziono wizyt w bazie</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}